name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/documentation.yml
permissions:
  contents: write
jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Create User Documentation
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: xdo
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true
      - name: Generate Tags
        run: |
          nvim -c 'helptags doc' -c 'quit'
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(vimdoc): auto-gen doc and tags"
          branch: ${{ github.head_ref }}
